# -*- coding:utf-8 -*-
# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases\demo_testcase_request.yml
_author_ = 'Leo'
__date__ = '2021/2/26 17:59'

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase
class TestCaseDemoTestcaseRequest(HttpRunner):

    config = (
        Config("获取商户首页模版")
            .variables(**{})
            .base_url("${ENV(base_url_wechat_online)}")
            .verify(False)
            .export(*["templateId1","templateType1"])
    )
    teststeps = [
        Step(
            RunRequest("获取商户首页模版-001")
                .with_variables(**{})
                .post("/indexApiService/getTemplate")
                .with_headers(
                **{
                    "User-Agent":"HttpRunner/${get_httprunner_version()}",
                    "Content-Type":"application/json",
                }
            )
                .with_params(
                **{
                    "vendorCode":"${ENV(vendorCode)}"
                }
            )
                .with_json({})
                .extract()
                .with_jmespath("body.data[0].id","templateId1")
                .with_jmespath("body.data[0].templateType","templateType1")
                .validate()
                .assert_equal("status_code",200)
                .assert_equal("body.msg","success")
        )
    ]