# NOTE: Generated By HttpRunner v3.1.4

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

class TestCaseDemoTestcaseRequest(HttpRunner):
    #用例配置
    config = (
        Config("登录模块")
            .variables(**{})  #指定用例参数
            .base_url("${ENV(base_url_vendor_develop_ui)}")  #访问域名
            .verify(False)  #是否验证服务器的TLS证书
            .export(*["productId"])   #导出用例变量
    )
    #测试步骤
    teststeps = [
        Step(
            RunRequest("IT_卖家端_登录模块_必填参数account未传_001")
            .with_variables(**{})
            .post("/users/loginCheck")
            .with_headers(
                **{
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "Content-Type": "application/x-www-form-urlencoded",
                }
            )
            .with_data(
                {
                    "cityCode": 132,
                    "cityName": "重庆市",
                    "lon": 106.53063501,
                    "lat": 29.54460611,
                    "memberType": "COMPANY",
                    "password": "123456",
                }
            )
            .extract()
            .validate()
            .assert_equal("status_code",200)
            .assert_equal("body.msg","登录异常")
        ),
        Step(
            RunRequest("IT_卖家端_登录模块_002")
            .with_variables(**{})
            .post("/users/loginCheck")
            .with_headers(
                **{
                    "User-Agent":"HttpRunner/${get_httprunner_version()}",
                    "Content-Type":"application/x-www-form-urlencoded",
                }
            )
            .with_data(
                {
                    "cityCode": 132,
                    "cityName": "重庆市",
                    "lon": 106.53063501,
                    "lat": 29.54460611,
                    "memberType": "COMPANY",
                    "account": "18000000003",
                    "password": "123456",
                }
            )
            .extract()
            .validate()
            .assert_equal("status_code",200)
            .assert_equal("body.msg","success")
        )
    ]


if __name__ == "__main__":
    TestCaseDemoTestcaseRequest().test_start()
