# -*- coding:utf-8 -*-
# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases\demo_testcase_request.yml
_author_ = 'Leo'
__date__ = '2021/2/26 16:49'

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase
class TestCaseDemoTestcaseRequest(HttpRunner):

    config = (
        Config("查询部分店铺")
        .variables(**{})
        .base_url("${ENV(base_url_wechat_develop_rest)}")
        .verify(False)
        .export(*[])
    )
    teststeps = [
        Step(
            RunRequest("查询部分店铺-001")
            .with_variables(**{})
            .post("/depot/searchNearDepot")
            .with_headers(
                **{
                    "User-Agent":"HttpRunner/${get_httprunner_version()}",
                    "Content-Type":"application/json",
                }
            )
            .with_json(
                {
                    "latitude": 28.449297,
                    "longitude": 109.001855,
                    "pageSize": 4,
                    "distance":2
                }
            )
            .extract()
            .with_jmespath("body.data.content[0].depotCode","depotCode")
            .with_jmespath("body.data.content[0].id","vendorId")
            .validate()
            .assert_equal("status_code",200)
            .assert_equal("body.msg","success")
        )
    ]

if __name__ == "__main__":
    TestCaseRequestWithFunctions().test_start()