# NOTE: Generated By HttpRunner v3.1.4
# FROM: har\demo.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseDemo(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/index.html")
            .get("https://vendor.wkhgs.com/index.html")
            .with_params(**{"sessionId": "bb96e637-3666-4e97-a537-2beacf34d463"})
            .with_headers(
                **{
                    "Host": "vendor.wkhgs.com",
                    "Connection": "keep-alive",
                    "Upgrade-Insecure-Requests": "1",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",
                    "Sec-Fetch-User": "?1",
                    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Mode": "navigate",
                    "Referer": "https://merch.wkhgs.com/",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "text/html")
        ),
    ]


if __name__ == "__main__":
    TestCaseDemo().test_start()
