# NOTE: Generated By HttpRunner v3.1.4
# FROM: har\loginCheck.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLogincheck(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/users/loginCheck")
            .post("https://merch.wkhgs.com/users/loginCheck")
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Content-Length": "149",
                    "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "Cookie": "webchat_visitor_guid=ee8a1bf0-dc0b-9c68-06a5-ceb9d4dd0af9; Authorization=799ca4a5-dd4d-4c72-9830-218404dbbb84; JSESSIONID=3ECB007664A308BF0BB1017444248EE3",
                    "Host": "merch.wkhgs.com",
                    "Origin": "https://merch.wkhgs.com",
                    "Referer": "https://merch.wkhgs.com/",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-origin",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",
                    "X-Requested-With": "XMLHttpRequest",
                }
            )
            .with_cookies(
                **{
                    "Authorization": "799ca4a5-dd4d-4c72-9830-218404dbbb84",
                    "JSESSIONID": "3ECB007664A308BF0BB1017444248EE3",
                    "webchat_visitor_guid": "ee8a1bf0-dc0b-9c68-06a5-ceb9d4dd0af9",
                }
            )
            .with_data(
                {
                    "account": "18000000003",
                    "cityCode": "132",
                    "cityName": "重庆市",
                    "lat": "29.54460611",
                    "lon": "106.53063501",
                    "memberType": "COMPANY",
                    "password": "123456",
                    "rememberMe": "",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "success")
            .assert_equal("body.ts", 1615775882603)
        ),
    ]


if __name__ == "__main__":
    TestCaseLogincheck().test_start()
