# NOTE: Generated By HttpRunner v3.1.4
# FROM: har\vendor.wkhgs.com.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseVendorWkhgsCom(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/index.html")
            .get("https://vendor.wkhgs.com/index.html")
            .with_params(**{"sessionId": "bbd5672c-d080-413c-98f2-f990ba73c042"})
            .with_headers(
                **{
                    "cache-control": "max-age=0",
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "if-modified-since": "Thu, 31 Dec 2020 09:18:08 GMT",
                }
            )
            .validate()
            .assert_equal("status_code", 304)
        ),
        Step(
            RunRequest("/api")
            .get("https://api.map.baidu.com/api")
            .with_params(
                **{"ak": "QtaGKiMKXEOANaGHm7cDnMbL", "v": "2.0", "services": "false"}
            )
            .with_headers(
                **{
                    "Host": "api.map.baidu.com",
                    "Connection": "keep-alive",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",
                    "Accept": "*/*",
                    "Sec-Fetch-Site": "cross-site",
                    "Sec-Fetch-Mode": "no-cors",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Cookie": "BIDUPSID=4F058D1C5CDE48DEA8FFC584F6598173; PSTM=1605089140; BAIDUID_BFESS=72B3414D0369E315C01BBF45C6F59160:FG=1; BAIDUID=59F566CD921DAF5BD0894F3F15C342A4:FG=1",
                }
            )
            .with_cookies(
                **{
                    "BIDUPSID": "4F058D1C5CDE48DEA8FFC584F6598173",
                    "PSTM": "1605089140",
                    "BAIDUID_BFESS": "72B3414D0369E315C01BBF45C6F59160:FG=1",
                    "BAIDUID": "59F566CD921DAF5BD0894F3F15C342A4:FG=1",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "text/javascript;charset=utf-8")
        ),
        Step(
            RunRequest("/static/css/app.f02955a2ce1116fdb423feebbf10aeed.css")
            .get(
                "https://vendor.wkhgs.com/static/css/app.f02955a2ce1116fdb423feebbf10aeed.css"
            )
            .with_headers(
                **{
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "text/css")
        ),
        Step(
            RunRequest("/static/js/manifest.67fcdc866550592f871e.js")
            .get("https://vendor.wkhgs.com/static/js/manifest.67fcdc866550592f871e.js")
            .with_headers(
                **{
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/javascript")
        ),
        Step(
            RunRequest("/static/js/vendor.949fac35875ffe7ee9e9.js")
            .get("https://vendor.wkhgs.com/static/js/vendor.949fac35875ffe7ee9e9.js")
            .with_headers(
                **{
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/javascript")
        ),
        Step(
            RunRequest("/static/js/app.f9cd01f5f584b944fdff.js")
            .get("https://vendor.wkhgs.com/static/js/app.f9cd01f5f584b944fdff.js")
            .with_headers(
                **{
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/javascript")
        ),
        Step(
            RunRequest("/getscript")
            .get("https://api.map.baidu.com/getscript")
            .with_params(
                **{
                    "v": "2.0",
                    "ak": "QtaGKiMKXEOANaGHm7cDnMbL",
                    "services": "false",
                    "t": "20210113094335",
                }
            )
            .with_headers(
                **{
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",
                    "Intervention": '<https://www.chromestatus.com/feature/5718547946799104>; level="warning"',
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "text/javascript;charset=utf-8")
        ),
        Step(
            RunRequest("/static/img/logo2.da05ab6.png")
            .get("https://vendor.wkhgs.com/static/img/logo2.da05ab6.png")
            .with_headers(
                **{
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "image/png")
        ),
        Step(
            RunRequest("/websocket")
            .get("wss://vendor.wkhgs.com/websocket")
            .with_params(**{"code": "VC10003"})
            .with_headers(
                **{
                    "Pragma": "no-cache",
                    "Origin": "https://vendor.wkhgs.com",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Host": "vendor.wkhgs.com",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Sec-WebSocket-Key": "3XiDD8REhRkXKhm0Q0b/Aw==",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",
                    "Upgrade": "websocket",
                    "Sec-WebSocket-Extensions": "permessage-deflate; client_max_window_bits",
                    "Cache-Control": "no-cache",
                    "Connection": "Upgrade",
                    "Sec-WebSocket-Version": "13",
                }
            )
            .validate()
            .assert_equal("status_code", 0)
        ),
        Step(
            RunRequest("/users/getMemberId")
            .options("https://venapi.wkhgs.com/users/getMemberId")
            .with_params(**{"Authorization": "bbd5672c-d080-413c-98f2-f990ba73c042"})
            .with_headers(
                **{
                    "access-control-request-method": "POST",
                    "origin": "https://vendor.wkhgs.com",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",
                    "access-control-request-headers": "content-type",
                    "accept": "*/*",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/users/getMemberId")
            .options("https://venapi.wkhgs.com/users/getMemberId")
            .with_params(**{"Authorization": "bbd5672c-d080-413c-98f2-f990ba73c042"})
            .with_headers(
                **{
                    "access-control-request-method": "POST",
                    "origin": "https://vendor.wkhgs.com",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",
                    "access-control-request-headers": "content-type",
                    "accept": "*/*",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/init")
            .post("https://venapi.wkhgs.com/init")
            .with_headers(
                **{
                    "content-length": "112",
                    "accept": "application/json, text/plain, */*",
                    "origin": "https://vendor.wkhgs.com",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",
                    "content-type": "application/json;charset=UTF-8",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(**{"JSESSIONID": "428D52905D16D87ECD8996933DE37C82"})
            .with_json(
                {
                    "memberId": "2501",
                    "userId": "2501",
                    "vendorId": "546520236057329664",
                    "depotCode": "VC10003",
                    "vendorCode": "VC10003",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "success")
            .assert_equal("body.ts", 1610697564140)
        ),
        Step(
            RunRequest("/users/getMemberId")
            .options("https://venapi.wkhgs.com/users/getMemberId")
            .with_params(**{"Authorization": "bbd5672c-d080-413c-98f2-f990ba73c042"})
            .with_headers(
                **{
                    "access-control-request-method": "POST",
                    "origin": "https://vendor.wkhgs.com",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",
                    "access-control-request-headers": "content-type",
                    "accept": "*/*",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/vendorRegister/getUserVendorRoleByUserId")
            .get("https://venapi.wkhgs.com/vendorRegister/getUserVendorRoleByUserId")
            .with_params(
                **{
                    "memberId": "2501",
                    "userId": "2501",
                    "vendorId": "546520236057329664",
                    "depotCode": "VC10003",
                    "vendorCode": "VC10003",
                }
            )
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "origin": "https://vendor.wkhgs.com",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(**{"JSESSIONID": "428D52905D16D87ECD8996933DE37C82"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "success")
            .assert_equal("body.ts", 1610697564154)
        ),
        Step(
            RunRequest("/vendorRegister/getUserVendorRoleByUserId")
            .get("https://venapi.wkhgs.com/vendorRegister/getUserVendorRoleByUserId")
            .with_params(
                **{
                    "memberId": "2501",
                    "userId": "2501",
                    "vendorId": "546520236057329664",
                    "depotCode": "VC10003",
                    "vendorCode": "VC10003",
                }
            )
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "origin": "https://vendor.wkhgs.com",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(**{"JSESSIONID": "428D52905D16D87ECD8996933DE37C82"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "success")
            .assert_equal("body.ts", 1610697564222)
        ),
        Step(
            RunRequest("/static/fonts/element-icons.535877f.woff")
            .get("https://vendor.wkhgs.com/static/fonts/element-icons.535877f.woff")
            .with_headers(
                **{
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",
                    "Referer": "https://vendor.wkhgs.com/static/css/app.f02955a2ce1116fdb423feebbf10aeed.css",
                    "Origin": "https://vendor.wkhgs.com",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/font-woff")
        ),
        Step(
            RunRequest("/order_info.mp3")
            .get("https://wkhgs.oss-cn-hangzhou.aliyuncs.com/order_info.mp3")
            .with_headers(
                **{
                    "Host": "wkhgs.oss-cn-hangzhou.aliyuncs.com",
                    "Connection": "keep-alive",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",
                    "Accept-Encoding": "identity;q=1, *;q=0",
                    "Accept": "*/*",
                    "Sec-Fetch-Site": "cross-site",
                    "Sec-Fetch-Mode": "no-cors",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Range": "bytes=0-",
                }
            )
            .validate()
            .assert_equal("status_code", 206)
            .assert_equal('headers."Content-Type"', "audio/mp3")
        ),
        Step(
            RunRequest("/")
            .get("https://api.map.baidu.com/")
            .with_params(
                **{
                    "qt": "verify",
                    "ak": "QtaGKiMKXEOANaGHm7cDnMbL",
                    "callback": "BMap._rd._cbk72527",
                }
            )
            .with_headers(
                **{
                    "Host": "api.map.baidu.com",
                    "Connection": "keep-alive",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",
                    "Accept": "*/*",
                    "Sec-Fetch-Site": "cross-site",
                    "Sec-Fetch-Mode": "no-cors",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Cookie": "BIDUPSID=4F058D1C5CDE48DEA8FFC584F6598173; PSTM=1605089140; BAIDUID_BFESS=72B3414D0369E315C01BBF45C6F59160:FG=1; BAIDUID=59F566CD921DAF5BD0894F3F15C342A4:FG=1",
                }
            )
            .with_cookies(
                **{
                    "BIDUPSID": "4F058D1C5CDE48DEA8FFC584F6598173",
                    "PSTM": "1605089140",
                    "BAIDUID_BFESS": "72B3414D0369E315C01BBF45C6F59160:FG=1",
                    "BAIDUID": "59F566CD921DAF5BD0894F3F15C342A4:FG=1",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal(
                'headers."Content-Type"', "application/javascript;charset=utf-8"
            )
        ),
        Step(
            RunRequest("/images/blank.gif")
            .get("https://api.map.baidu.com/images/blank.gif")
            .with_params(
                **{
                    "product": "jsapi",
                    "sub_product": "jsapi",
                    "v": "2.0",
                    "sub_product_v": "2.0",
                    "t": "55257680",
                    "code": "5000",
                    "da_src": "5000",
                    "device_pixel_ratio": "1",
                    "platform": "Win32",
                }
            )
            .with_headers(
                **{
                    "Host": "api.map.baidu.com",
                    "Connection": "keep-alive",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",
                    "Accept": "image/webp,image/apng,image/*,*/*;q=0.8",
                    "Sec-Fetch-Site": "cross-site",
                    "Sec-Fetch-Mode": "no-cors",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Cookie": "BIDUPSID=4F058D1C5CDE48DEA8FFC584F6598173; PSTM=1605089140; BAIDUID_BFESS=72B3414D0369E315C01BBF45C6F59160:FG=1; BAIDUID=59F566CD921DAF5BD0894F3F15C342A4:FG=1",
                }
            )
            .with_cookies(
                **{
                    "BIDUPSID": "4F058D1C5CDE48DEA8FFC584F6598173",
                    "PSTM": "1605089140",
                    "BAIDUID_BFESS": "72B3414D0369E315C01BBF45C6F59160:FG=1",
                    "BAIDUID": "59F566CD921DAF5BD0894F3F15C342A4:FG=1",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "image/gif")
        ),
        Step(
            RunRequest("/vendorRegister/getDetail")
            .get("https://venapi.wkhgs.com/vendorRegister/getDetail")
            .with_params(
                **{
                    "memberId": "2501",
                    "userId": "2501",
                    "vendorId": "546520236057329664",
                    "depotCode": "VC10003",
                    "vendorCode": "VC10003",
                }
            )
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "origin": "https://vendor.wkhgs.com",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(**{"JSESSIONID": "428D52905D16D87ECD8996933DE37C82"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "success")
            .assert_equal("body.ts", 1610697564151)
        ),
        Step(
            RunRequest("/vendorOrder/queryOrderListBySeller")
            .post("https://venapi.wkhgs.com/vendorOrder/queryOrderListBySeller")
            .with_headers(
                **{
                    "content-length": "151",
                    "accept": "application/json, text/plain, */*",
                    "origin": "https://vendor.wkhgs.com",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",
                    "content-type": "application/json;charset=UTF-8",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(**{"JSESSIONID": "428D52905D16D87ECD8996933DE37C82"})
            .with_json(
                {
                    "depotCode": "VC10003",
                    "page": 1,
                    "size": 10,
                    "state": "WAIT_SELF",
                    "memberId": "2501",
                    "userId": "2501",
                    "vendorId": "546520236057329664",
                    "vendorCode": "VC10003",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "success")
            .assert_equal("body.ts", 1610697564186)
        ),
        Step(
            RunRequest("/vendorRegister/getDetail")
            .get("https://venapi.wkhgs.com/vendorRegister/getDetail")
            .with_params(
                **{
                    "vendorId": "546520236057329664",
                    "memberId": "2501",
                    "userId": "2501",
                    "depotCode": "VC10003",
                    "vendorCode": "VC10003",
                }
            )
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "origin": "https://vendor.wkhgs.com",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(**{"JSESSIONID": "428D52905D16D87ECD8996933DE37C82"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "success")
            .assert_equal("body.ts", 1610697564148)
        ),
        Step(
            RunRequest("/static/img/weixin_code.7ce84fe.jpg")
            .get("https://vendor.wkhgs.com/static/img/weixin_code.7ce84fe.jpg")
            .with_headers(
                **{
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "image/jpeg")
        ),
        Step(
            RunRequest("/vendorOrder/queryOrderListBySeller")
            .post("https://venapi.wkhgs.com/vendorOrder/queryOrderListBySeller")
            .with_headers(
                **{
                    "content-length": "255",
                    "accept": "application/json, text/plain, */*",
                    "origin": "https://vendor.wkhgs.com",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",
                    "content-type": "application/json;charset=UTF-8",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(**{"JSESSIONID": "428D52905D16D87ECD8996933DE37C82"})
            .with_json(
                {
                    "page": 1,
                    "size": 10,
                    "startTime": None,
                    "endTime": None,
                    "mobile": None,
                    "orderCode": None,
                    "isOnline": "ON_LINE",
                    "isPreSale": "0",
                    "scatteredStatus": "yes",
                    "memberId": "2501",
                    "userId": "2501",
                    "vendorId": "546520236057329664",
                    "depotCode": "VC10003",
                    "vendorCode": "VC10003",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "success")
            .assert_equal("body.ts", 1610697564414)
        ),
        Step(
            RunRequest("/users/getMemberId")
            .post("https://venapi.wkhgs.com/users/getMemberId")
            .with_params(**{"Authorization": "bbd5672c-d080-413c-98f2-f990ba73c042"})
            .with_headers(
                **{
                    "content-length": "112",
                    "accept": "application/json, text/plain, */*",
                    "origin": "https://vendor.wkhgs.com",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",
                    "content-type": "application/json;charset=UTF-8",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(**{"JSESSIONID": "428D52905D16D87ECD8996933DE37C82"})
            .with_json(
                {
                    "memberId": "2501",
                    "userId": "2501",
                    "vendorId": "546520236057329664",
                    "depotCode": "VC10003",
                    "vendorCode": "VC10003",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "success")
            .assert_equal("body.ts", 1610697564276)
        ),
        Step(
            RunRequest("/users/getMemberId")
            .post("https://venapi.wkhgs.com/users/getMemberId")
            .with_params(**{"Authorization": "bbd5672c-d080-413c-98f2-f990ba73c042"})
            .with_headers(
                **{
                    "content-length": "112",
                    "accept": "application/json, text/plain, */*",
                    "origin": "https://vendor.wkhgs.com",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",
                    "content-type": "application/json;charset=UTF-8",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(**{"JSESSIONID": "428D52905D16D87ECD8996933DE37C82"})
            .with_json(
                {
                    "memberId": "2501",
                    "userId": "2501",
                    "vendorId": "546520236057329664",
                    "depotCode": "VC10003",
                    "vendorCode": "VC10003",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "success")
            .assert_equal("body.ts", 1610697564279)
        ),
        Step(
            RunRequest("/users/getMemberId")
            .post("https://venapi.wkhgs.com/users/getMemberId")
            .with_params(**{"Authorization": "bbd5672c-d080-413c-98f2-f990ba73c042"})
            .with_headers(
                **{
                    "content-length": "112",
                    "accept": "application/json, text/plain, */*",
                    "origin": "https://vendor.wkhgs.com",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",
                    "content-type": "application/json;charset=UTF-8",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(**{"JSESSIONID": "428D52905D16D87ECD8996933DE37C82"})
            .with_json(
                {
                    "memberId": "2501",
                    "userId": "2501",
                    "vendorId": "546520236057329664",
                    "depotCode": "VC10003",
                    "vendorCode": "VC10003",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "success")
            .assert_equal("body.ts", 1610697564298)
        ),
        Step(
            RunRequest("/vendorRegister/getUserVendorRoleByUserId")
            .get("https://venapi.wkhgs.com/vendorRegister/getUserVendorRoleByUserId")
            .with_params(
                **{
                    "userId": "2501",
                    "memberId": "2501",
                    "vendorId": "546520236057329664",
                    "depotCode": "VC10003",
                    "vendorCode": "VC10003",
                }
            )
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "origin": "https://vendor.wkhgs.com",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(**{"JSESSIONID": "07D47496D9147E81173505E3AD1888B0"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "success")
            .assert_equal("body.ts", 1610697564336)
        ),
        Step(
            RunRequest("/ac3a21b4-61e0-4ecc-8d1e-02c1326b67ba")
            .get(
                "https://wkhgs.oss-cn-hangzhou.aliyuncs.com/ac3a21b4-61e0-4ecc-8d1e-02c1326b67ba"
            )
            .with_headers(
                **{
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/octet-stream")
        ),
        Step(
            RunRequest("/f4a65feb-457d-42e9-9baf-6d0bb2ec03ab")
            .get(
                "https://wkhgs.oss-cn-hangzhou.aliyuncs.com/f4a65feb-457d-42e9-9baf-6d0bb2ec03ab"
            )
            .with_headers(
                **{
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/octet-stream")
        ),
        Step(
            RunRequest("/2b23217a-0838-4349-b930-7e50c905aa4d")
            .get(
                "https://wkhgs.oss-cn-hangzhou.aliyuncs.com/2b23217a-0838-4349-b930-7e50c905aa4d"
            )
            .with_headers(
                **{
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/octet-stream")
        ),
        Step(
            RunRequest("/0d6c935c-ab5f-4d1c-8131-90c9ef6e8ba6")
            .get(
                "https://wkhgs.oss-cn-hangzhou.aliyuncs.com/0d6c935c-ab5f-4d1c-8131-90c9ef6e8ba6"
            )
            .with_headers(
                **{
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/octet-stream")
        ),
        Step(
            RunRequest("/adfdc966-11c0-4075-a808-7dcc5ac0f3f5")
            .get(
                "https://wkhgs.oss-cn-hangzhou.aliyuncs.com/adfdc966-11c0-4075-a808-7dcc5ac0f3f5"
            )
            .with_headers(
                **{
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/octet-stream")
        ),
        Step(
            RunRequest("/9493478b-2d4f-4312-844c-1c5edc7d8c56")
            .get(
                "https://wkhgs.oss-cn-hangzhou.aliyuncs.com/9493478b-2d4f-4312-844c-1c5edc7d8c56"
            )
            .with_headers(
                **{
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/octet-stream")
        ),
        Step(
            RunRequest("/f159727b-9059-47fe-b9da-d6182caf432f")
            .get(
                "https://wkhgs.oss-cn-hangzhou.aliyuncs.com/f159727b-9059-47fe-b9da-d6182caf432f"
            )
            .with_headers(
                **{
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/octet-stream")
        ),
    ]


if __name__ == "__main__":
    TestCaseVendorWkhgsCom().test_start()
