# -*- coding:utf-8 -*-
# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases\demo_testcase_request.yml
_author_ = 'Leo'
__date__ = '2021/2/26 17:35'

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase
from testcases.wechat.search.searchNearDepot_test import (TestCaseDemoTestcaseRequest as RequestWithFunctions)
class TestCaseDemoTestcaseRequest(HttpRunner):

    config = (
        Config("一键领取优惠券")
        .variables(**{})
        .base_url("${ENV(base_url_wechat_develop_rest)}")
        .verify(False)
        .export(*[])
    )
    teststeps = [
        Step(
            RunTestCase("导出变量")
            .call(RequestWithFunctions)
            .export(*["vendorId","depotCode"])
        ),
        Step(
            RunRequest("一键领取优惠券-001")
            .with_variables(**{})
            .post("/indexApiService/oneClickGetCoupon")
            .with_headers(
                **{
                    "User-Agent":"HttpRunner/${get_httprunner_version()}",
                    "Content-Type":"application/json",
                }
            )
            .with_json(
                {
                    "vendorId": "$vendorId",
                    "vendorCode": "$depotCode",
                    "userId": "${ENV(memberId)}"
                }
            )
            .validate()
            .assert_equal("status_code",200)
            .assert_equal("body.msg","领取成功")
        )
    ]

if __name__ == "__main__":
    TestCaseRequestWithFunctions().test_start()